spring:
  application:
    name:
      CourseShop
  datasource:
    url: jdbc:postgresql://localhost:5432/Course
    username: postgres
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
server:
  port: 8080
  servlet:
    context-path: /CourseShop
